## Memory

In [7]:
import numpy as np
import sys

ls = [1,2,3,4]
np_arr = np.array(ls)

print("Memory Consumed by Lists: ", sys.getsizeof(ls), "Bytes")
print("Memory Consumed by NumPy: ", np_arr.itemsize*np_arr.size, "Bytes")

Memory Consumed by Lists:  96 Bytes
Memory Consumed by NumPy:  16 Bytes


## Pointers

- ==: Equality Operator
- is: Identity Operator

In [11]:
ls

[1, 2, 3, 4]

In [12]:
np_arr

array([1, 2, 3, 4])

In [14]:
ls[0] == ls[0]

True

In [15]:
np_arr[0] == np_arr[0]

True

In [16]:
ls[0] is ls[0]

True

In [17]:
np_arr[0] is np_arr[0]

False

## Speed

In [19]:
import time

ls1 = [i for i in range(1000000)]
np_arr1 = np.array(ls1)

t1 = time.time()
ls2 = [i+2 for i in ls1]
t2 = time.time()

print("The total time take by lists operations: ", (t2-t1)*1000, "ms")

t3 = time.time()
np_arr2 = np_arr1+2
t4 = time.time()

print("The total time taken by the NumPy array operations ", (t4-t3)*1000, "ms")

The total time take by lists operations:  285.19225120544434 ms
The total time taken by the NumPy array operations  6.004810333251953 ms


## NumPy Basics

In [20]:
ls = [1,2,3,"sumit", True]

In [21]:
np.array(ls)

array(['1', '2', '3', 'sumit', 'True'], dtype='<U11')

In [22]:
ls1 = [1,2,3,4,5,6]
ar1 = np.array(ls1)

In [23]:
# Rank-1/ 1D Array
ar1

array([1, 2, 3, 4, 5, 6])

In [24]:
# This NumPy array is having 6 elements
# Not having rows and columns
ar1.shape

(6,)

In [28]:
# I can't say that ar1 is having 1 row and 6 column. 
ls3 = [[1,2,3,4,5,6]]
ar3 = np.array(ls3)

In [29]:
ar3

array([[1, 2, 3, 4, 5, 6]])

In [30]:
ar3.shape

(1, 6)

In [32]:
np.array([[1], [2], [3], [4], [5], [6]]).shape

(6, 1)

In [25]:
ls = [[1,2,3], [4,5,6], [7,8,9]]
ar2 = np.array(ls)

In [26]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# 2-d array
# with 3 rows and 3 columns
ar2.shape

(3, 3)

In [34]:
## 3-D ARRAY

import cv2
img = cv2.imread('mother_teresa.jpg')
img.shape

(600, 640, 3)

### Inspecting a numpy array

In [37]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
print("Number of Dimensions", ar2.ndim)
print("Shape of array", ar2.shape)
print("Size of the array", ar2.size)
print("Data type of each element of the array", ar2.dtype)
print("Memory consumed by each element of your numpy array", ar2.itemsize, "Bytes")
print("The total memory consumed by numpy array", ar2.nbytes, "Bytes")

Number of Dimensions 2
Shape of array (3, 3)
Size of the array 9
Data type of each element of the array int32
Memory consumed by each element of your numpy array 4 Bytes
The total memory consumed by numpy array 36 Bytes


### Slicing and Indexing Array's

In [41]:
ar1

array([1, 2, 3, 4, 5, 6])

In [42]:
ar1[0]

1

In [43]:
ar1[-1]

6

In [44]:
ar1[0:5]

array([1, 2, 3, 4, 5])

In [45]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
# ar2[# range of rows , # range of columns]
ar2[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [47]:
ar2[0::2, 0::2]

array([[1, 3],
       [7, 9]])

In [48]:
ar1

array([1, 2, 3, 4, 5, 6])

In [57]:
ar1[0:1]

array([1])

In [50]:
ar1[::2]
# start from very start
# go upto very end
# extract every altenative. 2nd element

array([1, 3, 5])

In [51]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
ar2[: , 0]
# All the rows
# COlumns 0

array([1, 4, 7])

In [53]:
ar2[:, :1]
# All the rows
#Col1

array([[1],
       [4],
       [7]])

In [60]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
ar2[0:1, 1:]
# Row-1
# Start from first column, go upto the last

array([[2, 3]])

In [61]:
ar1

array([1, 2, 3, 4, 5, 6])

In [62]:
ar1[0:3]

array([1, 2, 3])

In [63]:
ar1[0]

1

In [64]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
ar2[0::2, 0::2]

array([[1, 3],
       [7, 9]])

### Functions

In [66]:
# arange
[i for i in range(1,10)]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [68]:
# NumPy array with an specified range
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# reshape
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
# returns random number between 0,1 in 3,4 shape
np.random.random((3,4))

array([[0.57763308, 0.22512472, 0.72695682, 0.68546517],
       [0.09463381, 0.65127699, 0.98057907, 0.90279751],
       [0.93628013, 0.52370872, 0.5399838 , 0.25326124]])

In [77]:
# return random integer between 1,10
np.random.randint(10)

5

In [78]:
# 10 random number between -inf to +inf
np.random.randn(10)

array([ 0.20114118,  2.07019721,  1.72877045, -1.0589721 , -0.57458311,
       -1.05943584,  0.4961517 ,  1.12851513, -0.51484289, -1.12557376])

In [80]:
# will return n numbers betwee cretain limit
np.linspace(15, 18, 25)
# starting
# ending
# number of elements

array([15.   , 15.125, 15.25 , 15.375, 15.5  , 15.625, 15.75 , 15.875,
       16.   , 16.125, 16.25 , 16.375, 16.5  , 16.625, 16.75 , 16.875,
       17.   , 17.125, 17.25 , 17.375, 17.5  , 17.625, 17.75 , 17.875,
       18.   ])

## Pandas

In [81]:
import pandas as pd

In [84]:
df = pd.read_csv(r"C:\Users\SUMITH\Python Notebooks\Python Notebooks\upGrad MBA\Live Session\Batch-1\telco_churn.csv")

In [83]:
r"C:\Users\SUMITH\Python Notebooks\Python Notebooks\upGrad MBA\Live Session\Batch-1\telco_churn.csv"

'C:\\Users\\SUMITH\\Python Notebooks\\Python Notebooks\\upGrad MBA\\Live Session\\Batch-1\\telco_churn.csv'

In [85]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [88]:
## Extract columns from your data frame
# Col  Name
type(df.customerID)

pandas.core.series.Series

In [90]:
type(df['customerID'])

pandas.core.series.Series

In [91]:
df.customerID

0       7590-VHVEG
1       5575-GNVDE
2       3668-QPYBK
3       7795-CFOCW
4       9237-HQITU
           ...    
7038    6840-RESVB
7039    2234-XADUH
7040    4801-JZAZL
7041    8361-LTMKD
7042    3186-AJIEK
Name: customerID, Length: 7043, dtype: object

### How to extract columns:
- df.colname
- df['colname']

### How to extract the subset out of a dataframe
- indexing
- iloc: index based slicing method
- loc: name based slicing method

In [92]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [97]:
# df[['customerID', 'gender', 'SeniorCitizen']].head(100)
df[['customerID', 'gender', 'SeniorCitizen']][:101]

customerID  gender  SeniorCitizen
0    7590-VHVEG  Female              0
1    5575-GNVDE    Male              0
2    3668-QPYBK    Male              0
3    7795-CFOCW    Male              0
4    9237-HQITU  Female              0
..          ...     ...            ...
96   9803-FTJCG    Male              0
97   0278-YXOOG    Male              0
98   3212-KXOCR    Male              0
99   4598-XLKNJ  Female              1
100  6380-ARCEH    Male              0

[101 rows x 3 columns]

In [100]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [101]:
# df.iloc[# range of rows: stepsize, # range of columns: stepsize]
df.iloc[0:100:2, 0::2]

customerID  SeniorCitizen Dependents PhoneService InternetService  \
0   7590-VHVEG              0         No           No             DSL   
2   3668-QPYBK              0         No          Yes             DSL   
4   9237-HQITU              0         No          Yes     Fiber optic   
6   1452-KIOVK              0        Yes          Yes     Fiber optic   
8   7892-POOKP              0         No          Yes     Fiber optic   
10  9763-GRSKD              0        Yes          Yes             DSL   
12  8091-TTVAX              0         No          Yes     Fiber optic   
14  5129-JLPIS              0         No          Yes     Fiber optic   
16  8191-XWSZG              0         No          Yes              No   
18  4190-MFLUW              0        Yes          Yes             DSL   
20  8779-QRDMV              1         No           No             DSL   
22  1066-JKSGK              0         No          Yes              No   
24  6322-HRPFA              0        Yes          Yes             DSL   
26  6467-CHFZW              0        Yes          Yes     Fiber optic   
28  5248-YGIJN              0         No          Yes             DSL   
30  3841-NFECX              1         No          Yes     Fiber optic   
32  6827-IEAUQ              0        Yes          Yes             DSL   
34  3413-BMNZE              1         No          Yes             DSL   
36  6047-YHPVI              0         No          Yes     Fiber optic   
38  5380-WJKOV              0         No          Yes     Fiber optic   
40  8865-TNMNX              0        Yes          Yes             DSL   
42  9867-JCZSP              0        Yes          Yes              No   
44  4080-IIARD              0         No          Yes             DSL   
46  5948-UJZLF              0         No          Yes             DSL   
48  7639-LIAYI              0         No          Yes             DSL   
50  8012-SOUDQ              1         No          Yes     Fiber optic   
52  6575-SUVOI              1         No          Yes             DSL   
54  4667-QONEA              1        Yes          Yes             DSL   
56  8769-KKTPH              0        Yes          Yes     Fiber optic   
58  3957-SQXML              0        Yes          Yes              No   
60  0434-CSFON              0         No          Yes     Fiber optic   
62  0526-SXDJP              0         No           No             DSL   
64  5698-BQJOH              0         No          Yes     Fiber optic   
66  8627-ZYGSZ              0         No          Yes     Fiber optic   
68  3170-NMYVV              0        Yes          Yes              No   
70  2273-QCKXA              0         No          Yes             DSL   
72  1891-QRQSA              1        Yes          Yes     Fiber optic   
74  5630-AHZIL              0        Yes          Yes             DSL   
76  6416-JNVRK              0         No          Yes             DSL   
78  0191-ZHSKZ              1         No          Yes             DSL   
80  5919-TMRGD              0        Yes          Yes     Fiber optic   
82  9191-MYQKX              0         No          Yes     Fiber optic   
84  0318-ZOPWS              0         No          Yes              No   
86  4808-YNLEU              0         No          Yes             DSL   
88  2796-NNUFI              0        Yes          Yes              No   
90  4767-HZZHQ              0        Yes          Yes     Fiber optic   
92  7233-PAHHL              0        Yes          Yes             DSL   
94  9848-JQJTX              0         No          Yes     Fiber optic   
96  9803-FTJCG              0        Yes          Yes             DSL   
98  3212-KXOCR              0         No          Yes              No   

           OnlineBackup          TechSupport      StreamingMovies  \
0                   Yes                   No                   No   
2                   Yes                   No                   No   
4                    No                   No                   No   
6   

In [102]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [103]:
df.iloc[[0,5,7],[2,5] ]

SeniorCitizen  tenure
0              0       1
5              0       8
7              0      10

In [104]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [105]:
df.loc[[0, 4], ["customerID", "gender", "Partner"]]

customerID  gender Partner
0  7590-VHVEG  Female     Yes
4  9237-HQITU  Female      No

In [107]:
df1 = df.set_index("customerID")
df1.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
customerID                                                                  
7590-VHVEG  Female              0     Yes         No       1           No   
5575-GNVDE    Male              0      No         No      34          Yes   
3668-QPYBK    Male              0      No         No       2          Yes   
7795-CFOCW    Male              0      No         No      45           No   
9237-HQITU  Female              0      No         No       2          Yes   

               MultipleLines InternetService OnlineSecurity OnlineBackup  \
customerID                                                                 
7590-VHVEG  No phone service             DSL             No          Yes   
5575-GNVDE                No             DSL            Yes           No   
3668-QPYBK                No             DSL            Yes          Yes   
7795-CFOCW  No phone service             DSL            Yes           No   
9237-HQITU                No     Fiber optic             No           No   

           DeviceProtection TechSupport StreamingTV StreamingMovies  \
customerID                                                            
7590-VHVEG               No          No          No              No   
5575-GNVDE              Yes          No          No              No   
3668-QPYBK               No          No          No              No   
7795-CFOCW              Yes         Yes          No              No   
9237-HQITU               No          No          No              No   

                  Contract PaperlessBilling              PaymentMethod  \
customerID                                                               
7590-VHVEG  Month-to-month              Yes           Electronic check   
5575-GNVDE        One year               No               Mailed check   
3668-QPYBK  Month-to-month              Yes               Mailed check   
7795-CFOCW        One year               No  Bank transfer (automatic)   
9237-HQITU  Month-to-month              Yes           Electronic check   

            MonthlyCharges TotalCharges Churn  
customerID                                     
7590-VHVEG           29.85        29.85    No  
5575-GNVDE           56.95       1889.5    No  
3668-QPYBK           53.85       108.15   Yes  
7795-CFOCW           42.30      1840.75    No  
9237-HQITU           70.70       151.65   Yes

In [108]:
df1.loc[['7590-VHVEG', '9237-HQITU'], ['gender','SeniorCitizen','Partner']]

gender  SeniorCitizen Partner
customerID                               
7590-VHVEG  Female              0     Yes
9237-HQITU  Female              0      No

In [110]:
df

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80        1990.5   
7039              Yes    Credit card (automatic)         103.20        7362.9   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 21 columns]

In [111]:
df.set_index("customerID", inplace = True)
# inplace = True: will make the operation permanent

In [114]:
df.reset_index(inplace = True)

In [115]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

## How to filter

In [117]:
df[df['gender']=='Male']

customerID gender  SeniorCitizen Partner Dependents  tenure  \
1     5575-GNVDE   Male              0      No         No      34   
2     3668-QPYBK   Male              0      No         No       2   
3     7795-CFOCW   Male              0      No         No      45   
6     1452-KIOVK   Male              0      No        Yes      22   
9     6388-TABGU   Male              0      No        Yes      62   
...          ...    ...            ...     ...        ...     ...   
7033  9767-FFLEM   Male              0      No         No      38   
7035  8456-QDAVC   Male              0      No         No      19   
7038  6840-RESVB   Male              0     Yes        Yes      24   
7041  8361-LTMKD   Male              1     Yes         No       4   
7042  3186-AJIEK   Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
6             Yes               Yes     Fiber optic             No  ...   
9             Yes                No             DSL            Yes  ...   
...           ...               ...             ...            ...  ...   
7033          Yes                No     Fiber optic             No  ...   
7035          Yes                No     Fiber optic             No  ...   
7038          Yes               Yes             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
6                  No          No         Yes              No  Month-to-month   
9                  No          No          No              No        One year   
...               ...         ...         ...             ...             ...   
7033               No          No          No              No  Month-to-month   
7035               No          No         Yes              No  Month-to-month   
7038              Yes         Yes         Yes             Yes        One year   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
6                 Yes    Credit card (automatic)          89.10        1949.4   
9                  No  Bank transfer (automatic)          56.15       3487.95   
...               ...                        ...            ...           ...   
7033              Yes    Credit card (automatic)          69.50       2625.25   
7035              Yes  Bank transfer (automatic)          78.70        1495.1   
7038              Yes               Mailed check          84.80        1990.5   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
1       No  
2      Yes  
3       No  
6       No  
9       No  
...    ...  
7033    No  
7035    No  
7038    No  
7041   Yes  
7042    No  

[3555 rows x 21 columns]

In [118]:
df[(df['gender']=='Male') & (df['SeniorCitizen']==0)]

customerID gender  SeniorCitizen Partner Dependents  tenure  \
1     5575-GNVDE   Male              0      No         No      34   
2     3668-QPYBK   Male              0      No         No       2   
3     7795-CFOCW   Male              0      No         No      45   
6     1452-KIOVK   Male              0      No        Yes      22   
9     6388-TABGU   Male              0      No        Yes      62   
...          ...    ...            ...     ...        ...     ...   
7027  0550-DCXLH   Male              0      No         No      13   
7033  9767-FFLEM   Male              0      No         No      38   
7035  8456-QDAVC   Male              0      No         No      19   
7038  6840-RESVB   Male              0     Yes        Yes      24   
7042  3186-AJIEK   Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
6             Yes               Yes     Fiber optic             No  ...   
9             Yes                No             DSL            Yes  ...   
...           ...               ...             ...            ...  ...   
7027          Yes                No             DSL             No  ...   
7033          Yes                No     Fiber optic             No  ...   
7035          Yes                No     Fiber optic             No  ...   
7038          Yes               Yes             DSL            Yes  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
6                  No          No         Yes              No  Month-to-month   
9                  No          No          No              No        One year   
...               ...         ...         ...             ...             ...   
7027               No         Yes         Yes             Yes  Month-to-month   
7033               No          No          No              No  Month-to-month   
7035               No          No         Yes              No  Month-to-month   
7038              Yes         Yes         Yes             Yes        One year   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
6                 Yes    Credit card (automatic)          89.10        1949.4   
9                  No  Bank transfer (automatic)          56.15       3487.95   
...               ...                        ...            ...           ...   
7027               No               Mailed check          73.35        931.55   
7033              Yes    Credit card (automatic)          69.50       2625.25   
7035              Yes  Bank transfer (automatic)          78.70        1495.1   
7038              Yes               Mailed check          84.80        1990.5   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
1       No  
2      Yes  
3       No  
6       No  
9       No  
...    ...  
7027    No  
7033    No  
7035    No  
7038    No  
7042    No  

[2981 rows x 21 columns]

In [126]:
df[     (df['gender']=='Male')     &    (df['Partner']=='No')    |  (df['Dependents'] =='No')]

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7035  8456-QDAVC    Male              0      No         No      19   
7036  7750-EYXWZ  Female              0      No         No      12   
7037  2569-WGERO  Female              0      No         No      72   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
0              No  No phone service             DSL                   No  ...   
1             Yes                No             DSL                  Yes  ...   
2             Yes                No             DSL                  Yes  ...   
3              No  No phone service             DSL                  Yes  ...   
4             Yes                No     Fiber optic                   No  ...   
...           ...               ...             ...                  ...  ...   
7035          Yes                No     Fiber optic                   No  ...   
7036           No  No phone service             DSL                   No  ...   
7037          Yes                No              No  No internet service  ...   
7041          Yes               Yes     Fiber optic                   No  ...   
7042          Yes                No     Fiber optic                  Yes  ...   

         DeviceProtection          TechSupport          StreamingTV  \
0                      No                   No                   No   
1                     Yes                   No                   No   
2                      No                   No                   No   
3                     Yes                  Yes                   No   
4                      No                   No                   No   
...                   ...                  ...                  ...   
7035                   No                   No                  Yes   
7036                  Yes                  Yes                  Yes   
7037  No internet service  No internet service  No internet service   
7041                   No                   No                   No   
7042                  Yes                  Yes                  Yes   

          StreamingMovies        Contract PaperlessBilling  \
0                      No  Month-to-month              Yes   
1                      No        One year               No   
2                      No  Month-to-month              Yes   
3                      No        One year               No   
4                      No  Month-to-month              Yes   
...                   ...             ...              ...   
7035                   No  Month-to-month              Yes   
7036                  Yes        One year               No   
7037  No internet service        Two year              Yes   
7041                   No  Month-to-month              Yes   
7042                  Yes        Two year              Yes   

                  PaymentMethod MonthlyCharges  TotalCharges Churn  
0              Electronic check          29.85         29.85    No  
1                  Mailed check          56.95        1889.5    No  
2                  Mailed check          53.85        108.15   Yes  
3     Bank transfer (automatic)          42.30       1840.75    No  
4              Electronic check          70.70        151.65   Yes  
...                         ...            ...           ...   ...  
7035  Bank transfer (automatic)          78.70        1495.1    No  
7036           Electronic check          6

In [127]:
df['gender']=='Male'

0       False
1        True
2        True
3        True
4       False
        ...  
7038     True
7039    False
7040    False
7041     True
7042     True
Name: gender, Length: 7043, dtype: bool

In [132]:
df.loc[(df['gender']=='Male'), ['gender', 'Partner']]

gender Partner
1      Male      No
2      Male      No
3      Male      No
6      Male      No
9      Male      No
...     ...     ...
7033   Male      No
7035   Male      No
7038   Male     Yes
7041   Male     Yes
7042   Male      No

[3555 rows x 2 columns]

## Sort and Groupby

In [134]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [135]:
df.sort_values("MonthlyCharges",ascending = False )

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
4586  7569-NMZYQ  Female              0     Yes        Yes      72   
2115  8984-HPEMB  Female              0      No         No      71   
3894  5989-AXPUC  Female              0     Yes         No      68   
4804  5734-EJKXG  Female              0      No         No      61   
5127  8199-ZLLSA    Male              0      No         No      67   
...          ...     ...            ...     ...        ...     ...   
6906  9945-PSVIP  Female              0     Yes        Yes      25   
1156  0621-CXBKL  Female              0      No         No      53   
6652  0827-ITJPH    Male              0      No         No      36   
1529  9764-REAFF  Female              0     Yes         No      59   
3719  6823-SIDFQ    Male              0      No         No      28   

     PhoneService MultipleLines InternetService       OnlineSecurity  ...  \
4586          Yes           Yes     Fiber optic                  Yes  ...   
2115          Yes           Yes     Fiber optic                  Yes  ...   
3894          Yes           Yes     Fiber optic                  Yes  ...   
4804          Yes           Yes     Fiber optic                  Yes  ...   
5127          Yes           Yes     Fiber optic                  Yes  ...   
...           ...           ...             ...                  ...  ...   
6906          Yes            No              No  No internet service  ...   
1156          Yes            No              No  No internet service  ...   
6652          Yes            No              No  No internet service  ...   
1529          Yes            No              No  No internet service  ...   
3719          Yes            No              No  No internet service  ...   

         DeviceProtection          TechSupport          StreamingTV  \
4586                  Yes                  Yes                  Yes   
2115                  Yes                  Yes                  Yes   
3894                  Yes                  Yes                  Yes   
4804                  Yes                  Yes                  Yes   
5127                  Yes                  Yes                  Yes   
...                   ...                  ...                  ...   
6906  No internet service  No internet service  No internet service   
1156  No internet service  No internet service  No internet service   
6652  No internet service  No internet service  No internet service   
1529  No internet service  No internet service  No internet service   
3719  No internet service  No internet service  No internet service   

          StreamingMovies  Contract PaperlessBilling  \
4586                  Yes  Two year              Yes   
2115                  Yes  Two year              Yes   
3894                  Yes  Two year               No   
4804                  Yes  One year              Yes   
5127                  Yes  One year              Yes   
...                   ...       ...              ...   
6906  No internet service  Two year              Yes   
1156  No internet service  Two year               No   
6652  No internet service  Two year              Yes   
1529  No internet service  Two year               No   
3719  No internet service  One year               No   

                  PaymentMethod MonthlyCharges  TotalCharges Churn  
4586  Bank transfer (automatic)         118.75       8672.45    No  
2115           Electronic check         118.65        8477.6    No  
3894               Mailed check         118.60       7990.05    No  
4804           Electronic check         118.60        7365.7    No  
5127  Bank transfer (automatic)         118.35       7804.15   Yes  
...                         ...            ...           ...   ...  
6906               Mailed check          18.70        383.65    No  
1156               Mailed check          18.70        1005.7    No  
6652    Credit card (automatic)          18.55           689    No  
1529  Bank transfer (aut

In [136]:
df.sort_values(["MonthlyCharges", "TotalCharges"],ascending = [False, True] )

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
4586  7569-NMZYQ  Female              0     Yes        Yes      72   
2115  8984-HPEMB  Female              0      No         No      71   
4804  5734-EJKXG  Female              0      No         No      61   
3894  5989-AXPUC  Female              0     Yes         No      68   
5127  8199-ZLLSA    Male              0      No         No      67   
...          ...     ...            ...     ...        ...     ...   
1156  0621-CXBKL  Female              0      No         No      53   
6906  9945-PSVIP  Female              0     Yes        Yes      25   
6652  0827-ITJPH    Male              0      No         No      36   
1529  9764-REAFF  Female              0     Yes         No      59   
3719  6823-SIDFQ    Male              0      No         No      28   

     PhoneService MultipleLines InternetService       OnlineSecurity  ...  \
4586          Yes           Yes     Fiber optic                  Yes  ...   
2115          Yes           Yes     Fiber optic                  Yes  ...   
4804          Yes           Yes     Fiber optic                  Yes  ...   
3894          Yes           Yes     Fiber optic                  Yes  ...   
5127          Yes           Yes     Fiber optic                  Yes  ...   
...           ...           ...             ...                  ...  ...   
1156          Yes            No              No  No internet service  ...   
6906          Yes            No              No  No internet service  ...   
6652          Yes            No              No  No internet service  ...   
1529          Yes            No              No  No internet service  ...   
3719          Yes            No              No  No internet service  ...   

         DeviceProtection          TechSupport          StreamingTV  \
4586                  Yes                  Yes                  Yes   
2115                  Yes                  Yes                  Yes   
4804                  Yes                  Yes                  Yes   
3894                  Yes                  Yes                  Yes   
5127                  Yes                  Yes                  Yes   
...                   ...                  ...                  ...   
1156  No internet service  No internet service  No internet service   
6906  No internet service  No internet service  No internet service   
6652  No internet service  No internet service  No internet service   
1529  No internet service  No internet service  No internet service   
3719  No internet service  No internet service  No internet service   

          StreamingMovies  Contract PaperlessBilling  \
4586                  Yes  Two year              Yes   
2115                  Yes  Two year              Yes   
4804                  Yes  One year              Yes   
3894                  Yes  Two year               No   
5127                  Yes  One year              Yes   
...                   ...       ...              ...   
1156  No internet service  Two year               No   
6906  No internet service  Two year              Yes   
6652  No internet service  Two year              Yes   
1529  No internet service  Two year               No   
3719  No internet service  One year               No   

                  PaymentMethod MonthlyCharges  TotalCharges Churn  
4586  Bank transfer (automatic)         118.75       8672.45    No  
2115           Electronic check         118.65        8477.6    No  
4804           Electronic check         118.60        7365.7    No  
3894               Mailed check         118.60       7990.05    No  
5127  Bank transfer (automatic)         118.35       7804.15   Yes  
...                         ...            ...           ...   ...  
1156               Mailed check          18.70        1005.7    No  
6906               Mailed check          18.70        383.65    No  
6652    Credit card (automatic)          18.55           689    No  
1529  Bank transfer (aut

In [137]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [139]:
df.groupby("gender").agg({"MonthlyCharges": 'mean','customerID':'count'})

MonthlyCharges  customerID
gender                            
Female       65.204243        3488
Male         64.327482        3555

In [141]:
df.groupby("gender")['MonthlyCharges'].mean()

gender
Female    65.204243
Male      64.327482
Name: MonthlyCharges, dtype: float64

In [142]:
pd.pivot_table(df, index = ['gender'], columns = ['Partner'], values = "MonthlyCharges", aggfunc = 'mean')

Partner         No        Yes
gender                       
Female   63.874111  66.622630
Male     60.058854  68.912398